version: "3.8"

services:
  django:
    image: manishng/carrot_python3.10.12sb_django4.2.2:v1.1
    #build: Dockerfile-carrot
    container_name: docker_carrot-container 
    environment:
      - PYTHONUNBUFFERED=1 
    working_dir: /usr/src/app 
    #command: bash -c "django-admin startproject core . && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "if [ ! -d ./core ]; then django-admin startproject core .; fi && python manage.py runserver 0.0.0.0:8000"
    #command: python manage.py createsuperuser
    #command: django-admin startproject core .
    #command: python -m django-admin
    #command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:alpine3.18
    restart: always
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #working_dir: /usr/src/app
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
